apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register')
]

apps/poke/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^poke/(?P<id>\d+)$', views.poke, name='poke'),
    url(r'^logout$', views.logout, name='logout')
]

pokes/urls.py
from django.conf.urls import url, include # Notice we added include
from django.contrib import admin
urlpatterns = [
    url(r'^', include('apps.login.urls',namespace='login')) ,
     url(r'^poke/', include('apps.poke.urls',namespace='poke')) 
    # And now we use the include function to pull in our first_app.urls...
]

apps/login/models.py
from __future__ import unicode_literals
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.db import models
import bcrypt
import datetime

# Create your models here.

class UserManager(models.Manager):
	def register(self, request):
		errors = {}

		if len(request.POST['name']) < 3:
			errors['nameshort'] = "Name is too short!"
		for s in request.POST['name']:
			if not s.isalpha():
				errors['namenotalpha'] = " Name can only be letters!"

		if len(request.POST['alias']) < 3:
			errors['alias'] = "Alias is too short!"

		try:
			validate_email(request.POST['email'])
		except ValidationError:
			errors['email'] = "Invalid email!"

		if len(request.POST['password']) < 8:
			errors['password'] = "Password too short!"

		if request.POST['password'] != request.POST['dblcheck']:
			errors['dblcheck'] = "Passwords do not match!"

		try:
			dbirth = datetime.datetime.strptime(request.POST['dob'], "%Y-%m-%d").strftime('%Y-%m-%d')
			if datetime.datetime.strptime(dbirth, "%Y-%m-%d") >= datetime.datetime.now():
				errors['dob'] = "Date of Birth must be before today!"
		except ValueError:
			errors['dob'] = "Incorrect date format!"

		return errors

	def login(self, request):
		errors = {}

		try:
			user = User.objects.get(email=request.POST['email'])
			password = request.POST['password'].encode()
			if not bcrypt.hashpw(password, user.password.encode()):
				errors['wrong'] = "Email/password don't match."

		except ObjectDoesNotExist:
			errors['wrong'] = "Email/password don't match."

		return errors


class User(models.Model):
	name = models.CharField(max_length=255)
	alias = models.CharField(max_length=255)
	email = models.CharField(max_length=255)
	password = models.CharField(max_length=100)
	dob = models.DateField()
	poked = models.BooleanField(default=0)
	created_at = models.DateField(auto_now_add=True)
	updated_at = models.DateField(auto_now=True)
	objects = UserManager()

apps/poke/models.py
from __future__ import unicode_literals

from django.db import models
from ..login.models import User

# Create your models here.

class Poke(models.Model):
	poker = models.ForeignKey('login.User', models.DO_NOTHING, related_name="Poker")
	pokee = models.ForeignKey('login.User', models.DO_NOTHING, related_name="Pokee")
	count = models.IntegerField()
	created_at = models.DateField(auto_now_add=True)
	updated_at = models.DateField(auto_now=True)

class PokeRef(models.Model):
	poker = models.ForeignKey('login.User', models.DO_NOTHING, related_name="PokerRef")
	pokeeref = models.ForeignKey('login.User', models.DO_NOTHING, related_name="PokeeRef")
	count = models.IntegerField()
	created_at = models.DateField(auto_now_add=True)
	updated_at = models.DateField(auto_now=True)

apps/login/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from .models import User
import bcrypt
import datetime

def index(request):
	return render(request, 'login/index.html')

def register(request):
	errors = User.objects.register(request)

	if len(errors) > 0:
		context = {
			'errors': errors
		}
		return render(request, 'login/index.html', context)

	else:
		password = request.POST['password'].encode()
		newpass = bcrypt.hashpw(password, bcrypt.gensalt())
		dbirth = datetime.datetime.strptime(request.POST['dob'], "%Y-%m-%d").strftime('%Y-%m-%d')
		User.objects.create(name=request.POST['name'], alias=request.POST['alias'], email=request.POST['email'], password=newpass, dob=dbirth)
		request.session['user'] = request.POST['email']
		return redirect(reverse('poke:dashboard'))

def login(request):
	errors = User.objects.login(request)

	if len(errors) > 0:
		context = {
			'errors': errors
		}
		return render(request, 'login/index.html', context)

	else:
		request.session['user'] = request.POST['email']
		return redirect(reverse('poke:dashboard'))

apps/poke/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.db.models import Count
from django.db.models import Sum
from ..login.models import User
from .models import Poke, PokeRef

# Create your views here.
def dashboard(request):
	currentUser = User.objects.get(email=request.session['user'])
	context = {
		'self' : currentUser,
		'users' : User.objects.all().exclude(email=request.session['user']),
		'selfcount' : PokeRef.objects.values('poker').distinct().filter(pokeeref=User.objects.get(email=request.session['user'])).count(),
		'eachcount' : PokeRef.objects.filter(pokeeref=currentUser),
		'pokees': Poke.objects.all().exclude(pokee=currentUser).annotate(summed=Sum('count')).order_by('pokee'),
		'notpoked': User.objects.filter(poked=False)
	}
	print context['eachcount']
	return render(request, 'poke/dashboard.html', context)

def poke(request, id):
	try:
		updated = Poke.objects.get(pokee=User.objects.get(id=id))
		updated.count += 1
		updated.save()
	except Poke.DoesNotExist:
		Poke.objects.create(poker=User.objects.get(email=request.session['user']), pokee=User.objects.get(id=id), count=1)
		nowpoked = User.objects.get(id=id)
		nowpoked.poked = True
		nowpoked.save()
	try:
		updated1 = PokeRef.objects.get(poker=User.objects.get(email=request.session['user']), pokeeref=User.objects.get(id=id))
		updated1.count += 1
		updated1.save()
	except PokeRef.DoesNotExist:
		PokeRef.objects.create(poker=User.objects.get(email=request.session['user']), pokeeref=User.objects.get(id=id), count=1)
		nowpoked1 = User.objects.get(id=id)
		nowpoked1.poked = True
		nowpoked1.save()
	return redirect(reverse('poke:dashboard'))

def logout(request):
	request.session.flush()
	return redirect(reverse('login:index'))

apps/login/templates/login/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Login/Register</title>
</head>
<body>
	<h1>Welcome!</h1>
	<h3>Register</h3>
	<form action="{% url 'login:register' %}" method="post">
		{% csrf_token %}
		Name: <input type="text" name="name">
		Alias: <input type="text" name="alias">
		Email: <input type="text" name="email">
		Password: <input type="password" name="password">
		Confirm PW: <input type="password" name="dblcheck">
		Date of Birth: <input type="text" name="dob">
		<input type="submit" value="Register">
		<h5>*Password should be at least 8 characters</h5>
	</form>
	<h3>Login</h3>
	<form action="{% url 'login:login' %}" method="post">
		{% csrf_token %}
		Email: <input type="text" name="email">
		Password: <input type="password" name="password">
		<input type="submit" value="Login">
	</form>
	{% for item in errors.values %}
	<p>{{item}}</p>
	{% endfor %}
</body>
</html>

apps/poke/templates/poke/dashboard.html
<!DOCTYPE html>
<html>
<head>
	<title>Poke Dashboard</title>
</head>
<body>
	<h7><a href="{% url 'poke:logout' %}">Logout</a></h7>
	<h1>Welcome, {{self.name}}!</h1>
	<h4>{{selfcount}} people poked you!</h4>
	<ul>
		{% for each in eachcount %}
		<li>{{each.poker.name}} poked you {{each.count}} times.</li>
		{% endfor %}
	</ul>
	<h4>People you may want to poke:</h4>
	<table>
		<thead>
			<th>Name</th>
			<th>Alias</th>
			<th>Email Address</th>
			<th>Poke History</th>
			<th>Action</th>
		</thead>
		{% for pokee in pokees %}
		<tr>
			<td>{{pokee.pokee.name}}</td>
			<td>{{pokee.pokee.alias}}</td>
			<td>{{pokee.pokee.email}}</td>
			<td>{{pokee.summed}}</td>
			<td><a href="{% url 'poke:poke' id=pokee.pokee.id %}"><button>Poke!</button></a></td>
		</tr>
		{% endfor %}
		{% for start in notpoked %}
		{% if start.email != request.session.user %}
		<tr>
			<td>{{start.name}}</td>
			<td>{{start.alias}}</td>
			<td>{{start.email}}</td>
			<td>0</td>
			<td><a href="{% url 'poke:poke' id=start.id %}"><button>Poke!</button></a></td>
		</tr>
		{% endif %}
		{% endfor %}
	</table>
</body>
</html>